### PR TITLE
Add matches for image files to ignore.

### LINKED ISSUE #7: Requires using the file-loader fail
React components that use webpack [file-loader](https://github.com/webpack/file-loader) for image files will fail in jest as well and should be removed.

### PR DESCRIPTION
**Pull request by gregz67**
Hi @atecarlos.  Please take a look at this change that adds support for ignoring image files using file-loader.
- Replace file-loader requires with ""
- Update README
- Bump version
- fixes #7

### CODE REVIEW

**Comment by atecarlos** [comment]
Hi @gregz67 . How are you using the images on your components? This code would actually break the tests on a current project I'm working on. Perhaps we can make it a configuration option?

**Comment by atecarlos** [comment]
As discussed on #7 , a good solution for this is to add a mock file for the image itself so you can reference its URL as a variable.

**Comment by gregz67** [comment]
Hi @atecarlos .  Here are some snippets of how image files might be referenced in a component:

```
SomeComponent.defaultProps = {
  src: require('./img/no-image-available.jpg')
};
```

```
class SomeComponent extends React.Component {
  render() {
    return (
      <div>
        <div>
          <OtherComponent/>
        </div>
        <div>
          <a href="/">
            <img
              src={ require('./img/logo_large.png') }
            />
          </a>
        </div>
      </div>
    );
  }
}
```

As you can see a replace with `""` in both these cases will help jest run these components cleanly.  How is the new replace for image files breaking your tests?

I'm not sure I follow your suggestion about adding a mock file?

**Comment by atecarlos** [comment]
You can add a mock file under the `__mocks__` folder. Something like "logo_large.png.js" and have that be a simple module that exports a value that you can then use for assertions in your test. In the code you provided, you would then be able to assert that you are reading the expected image into the "src" attribute of your img.

In components/**mocks**/logo.png.js
`module.exports = 'logo-url';`

In components/header.react.js
`var logo = require('logo.png';)`
`...`
``

In your case, I think putting a `__mocks__` folder in your "img/" folder should do the trick. If not, you can leverage webpack configuration to simplify the path of your image file when requiring it to something like what I wrote above and leveraging the current directories `__mocks__` folder.

**Comment by gregz67** [comment]
Thanks @atecarlos! This is a really good suggestion.

One detail is that the mock image file would have to have the same file extension as the image file.  However, if you use an `index.js` file to map the `require` to a const instead, it works well.

Fixes #7

**Pull request closed without merging**
